version: "3.3"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app

  app:
    container_name: app
    image: node-app
    build: ./node
    volumes:
      - ./node:/home/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - node-network
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret

networks:
  node-network:
    driver: bridge
