apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: osor1o/hello-go:v12
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          # initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          # initialDelaySeconds: 15
        volumeMounts:
          - mountPath: "/go/pvc"
            name: goserver-volume
          - mountPath: /go/myfamily
            name: config
            readOnly: true
        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        # env:
        # - name: NAME
          # value: "Julia"
          # valueFrom:
          #   configMapKeyRef:
          #     name: goserver-env
          #     key: NAME
        # - name: AGE
          # value: "15"
          # valueFrom:
          #   configMapKeyRef:
          #     name: goserver-env
          #     key: AGE
        resources:
          requests: # Minimum
            cpu: 50m # 1000m = 1 vCPU | m = milicores | 100m = 0.1 (%)
            memory: 20Mi # M = Megabyte = 10^6B | Mi = Mebibyte = 2^20B
          limits: # Maximum
            memory: 25Mi
            cpu: 50m
      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt
