apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: osor1o/hello-go:v6
        volumeMounts:
          - mountPath: /go/myfamily
            name: config
            readOnly: true
        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        # env:
        # - name: NAME
          # value: "Julia"
          # valueFrom:
          #   configMapKeyRef:
          #     name: goserver-env
          #     key: NAME
        # - name: AGE
          # value: "15"
          # valueFrom:
          #   configMapKeyRef:
          #     name: goserver-env
          #     key: AGE
        resources:
          requests:
            memory: 64M
            cpu: 100m
          limits:
            memory: 128M
            cpu: 250m
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt
