apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
  - name: goserver
    image: "osor1o/hello-go"
    resources:
      requests:
        memory: 64M
        cpu: 100m
      limits:
        memory: 128M
        cpu: 250m
