apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 10
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: osor1o/hello-go:v2
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            memory: 25Mi
            cpu: 500m
